// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: go_crm_user_c.sql

package database

import (
	"context"
	"database/sql"
)

const getUserByEmailSQLC = `-- name: GetUserByEmailSQLC :one
Select usr_email, usr_id
from ` + "`" + `go_crm_user` + "`" + `
where usr_email = ? limit 1
`

type GetUserByEmailSQLCRow struct {
	UsrEmail string
	UsrID    sql.NullInt32
}

func (q *Queries) GetUserByEmailSQLC(ctx context.Context, usrEmail string) (GetUserByEmailSQLCRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailSQLC, usrEmail)
	var i GetUserByEmailSQLCRow
	err := row.Scan(&i.UsrEmail, &i.UsrID)
	return i, err
}

const updateUserStatusByUserID = `-- name: UpdateUserStatusByUserID :exec
Update ` + "`" + `go_crm_user` + "`" + `
set usr_status = $2,
    usr_updated_at = $3
where usr_id = $1
`

func (q *Queries) UpdateUserStatusByUserID(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateUserStatusByUserID)
	return err
}
