// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type GoCrmUser struct {
	// Account ID
	UsrID sql.NullInt32
	// Email
	UsrEmail string
	// Phone
	UsrPhone string
	// Username
	UsrUsername string
	// Hashed Password
	UsrPassword string
	// Created Time
	UsrCreatedAt sql.NullInt64
	// Updated Time
	UsrUpdatedAt sql.NullInt64
	// Created IP
	UsrCreateIpAt sql.NullString
	// Last Login Time
	UsrLastLoginAt sql.NullInt64
	// Last Login IP
	UsrLastLoginIpAt sql.NullString
	// Login Times
	UsrLoginTimes sql.NullInt32
	// 1:active,0:inactive
	UsrStatus sql.NullInt16
}
